spring:
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory database URL (can be changed to MySQL, PostgreSQL, etc.)
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create/update the database schema
    database-platform: org.hibernate.dialect.H2Dialect  
  h2:
    console:
      enabled: true  
  datasource:
    initialization-mode: always

# Server configuration (optional, depending on your needs)
server:
  port: 8080 
  servlet:
    context-path: /banking  
